In [19]:
import pandas as pd

In [20]:
df = pd.read_csv("data/BTCUSD/minutes.csv")

In [21]:
df.dtypes

time             int64
open           float64
high           float64
low            float64
close          float64
tick_volume      int64
spread           int64
real_volume      int64
dtype: object

In [22]:
(df['high'] - df['low']).min()

0.0

In [23]:
print(df.isna().any().any())

False

In [24]:
df.head()

         time   open   high    low  close  tick_volume  spread  real_volume
0  1357084800  13.36  13.40  13.16  13.28          401       0            0
1  1357171200  13.28  13.46  13.25  13.40          301       0            0
2  1357257600  13.43  13.52  13.27  13.50          431       0            0
3  1357516800  13.51  13.59  13.40  13.59          301       0            0
4  1357603200  13.55  13.88  13.50  13.74          571       0            0

Some of the initial rows are larger than a minute. Clearing those initial rows

In [25]:
cut_off = df.index[df['time'].shift(-1) - df['time'] == 60].min()
print(cut_off)

2910

In [26]:
df['time_diff'] = df['time'].shift(-1) - df['time']

In [27]:
df.head()

,time,open,high,low,close,tick_volume,spread,real_volume,time_diff
0,1357084800,13.36,13.40,13.16,13.28,401,0,0,86400.0
1,1357171200,13.28,13.46,13.25,13.40,301,0,0,86400.0
2,1357257600,13.43,13.52,13.27,13.50,431,0,0,259200.0
3,1357516800,13.51,13.59,13.40,13.59,301,0,0,86400.0
4,1357603200,13.55,13.88,13.50,13.74,571,0,0,86400.0

In [28]:
cut_off = df.index[df['time_diff'] == 60].min()
cut_off

2910

In [29]:
df[cut_off:].head()

,time,open,high,low,close,tick_volume,spread,real_volume,time_diff
2910,1497479940,2347.57,2362.63,2346.05,2353.00,27731,0,0,60.0
2911,1497480000,2353.00,2356.39,2344.09,2353.90,23701,0,0,60.0
2912,1497480060,2353.88,2356.28,2345.50,2345.51,13191,0,0,60.0
2913,1497480120,2351.00,2351.88,2344.03,2346.17,10871,0,0,60.0
2914,1497480180,2343.77,2343.77,2326.77,2326.77,17001,0,0,60.0

In [36]:
def small_df(df):
    return df[-10:]

In [37]:
df = small_df(df)

In [38]:
df

,time,open,high,low,close,tick_volume,spread,real_volume,time_diff
2808990,1712684340,69518.16,69518.16,69319.11,69325.31,77,9381,0,60.0
2808991,1712684400,69323.10,69365.94,69181.24,69297.22,75,9381,0,60.0
2808992,1712684460,69271.63,69340.96,69068.86,69123.33,63,9381,0,60.0
2808993,1712684520,69113.15,69113.15,68865.12,68970.79,63,9381,0,60.0
2808994,1712684580,68983.16,69187.82,68963.11,69151.75,65,9381,0,60.0
2808995,1712684640,69168.54,69168.54,68993.32,69123.86,72,9381,0,60.0
2808996,1712684700,69137.08,69249.42,69104.22,69185.40,78,9381,0,60.0
2808997,1712684760,69232.69,69232.69,68984.10,69039.11,68,9381,0,60.0
2808998,1712684820,69065.37,69067.11,68988.23,69052.12,84,9381,0,60.0
2808999,1712684880,69085.06,69090.92,68596.08,68711.33,57,9381,0,NaN