In [1]:
import pandas as pd
from process_data import clean_cols, clean_non_minute_rows, normalize_by_window, label_df

In [2]:
df = pd.read_csv("data/GBPUSD/minutes.csv")

In [3]:
df = clean_cols(df)

In [4]:
df.head()

        time    open    high     low   close
0  915433980  1.6686  1.6686  1.6686  1.6686
1  915434040  1.6682  1.6685  1.6682  1.6685
2  915434100  1.6689  1.6689  1.6689  1.6689
3  915434160  1.6687  1.6687  1.6685  1.6685
4  915434220  1.6691  1.6691  1.6691  1.6691

In [5]:
df = clean_non_minute_rows(df)

In [6]:
df.head()

        time    open    high     low   close
0  915433980  1.6686  1.6686  1.6686  1.6686
1  915434040  1.6682  1.6685  1.6682  1.6685
2  915434100  1.6689  1.6689  1.6689  1.6689
3  915434160  1.6687  1.6687  1.6685  1.6685
4  915434220  1.6691  1.6691  1.6691  1.6691

In [7]:
df = normalize_by_window(df)

In [8]:
df.head()

,time,open,high,low,close,open_normalized,high_normalized,low_normalized,close_normalized
1440,915553920,1.6561,1.6561,1.6542,1.6542,0.167539,0.167539,0.068063,0.068063
1441,915553980,1.6548,1.6550,1.6540,1.6544,0.099476,0.109948,0.057592,0.078534
1442,915554040,1.6547,1.6551,1.6545,1.6551,0.094241,0.115183,0.083770,0.115183
1443,915554100,1.6548,1.6548,1.6541,1.6547,0.099476,0.099476,0.062827,0.094241
1444,915554160,1.6553,1.6558,1.6550,1.6558,0.125654,0.151832,0.109948,0.151832

In [9]:
df = label_df(df)

In [10]:
df.tail(60)

,time,open,high,low,close,open_normalized,high_normalized,low_normalized,close_normalized,target
8982614,1712576820,1.26180,1.26200,1.26178,1.26197,0.631206,0.659574,0.628369,0.655319,0
8982615,1712576880,1.26197,1.26205,1.26197,1.26201,0.655319,0.666667,0.655319,0.660993,0
8982616,1712576940,1.26201,1.26209,1.26197,1.26197,0.660993,0.672340,0.655319,0.655319,0
8982617,1712577000,1.26198,1.26213,1.26198,1.26203,0.656738,0.678014,0.656738,0.663830,0
8982618,1712577060,1.26203,1.26215,1.26203,1.26207,0.663830,0.680851,0.663830,0.669504,0
8982619,1712577120,1.26208,1.26208,1.26201,1.26204,0.670922,0.670922,0.660993,0.665248,0
8982620,1712577180,1.26210,1.26223,1.26210,1.26223,0.673759,0.692199,0.673759,0.692199,0
8982621,1712577240,1.26223,1.26227,1.26199,1.26202,0.692199,0.697872,0.658156,0.662411,0
8982622,1712577300,1.26202,1.26211,1.26192,1.26192,0.662411,0.675177,0.648227,0.648227,0
8982623,1712577360,1.26192,1.26193,1.26182,1.26192,0.648227,0.649645,0.634043,0.648227,0
8982624,1712577420,1.26191,1.26193,1.26179,1.26190,0.646809,0.649645,0.629787,0.645390,0
8982625,1712577480,1.26191,1.26205,1.26189,1.26201,0.646809,0.666667,0.643972,0.660993,0
8982626,1712577540,1.26202,1.26212,1.26201,1.26207,0.662411,0.676596,0.660993,0.669504,0
8982627,1712577600,1.26209,1.26215,1.26197,1.26198,0.672340,0.680851,0.655319,0.656738,0
8982628,1712577660,1.26198,1.26212,1.26198,1.26203,0.656738,0.676596,0.656738,0.663830,0
8982629,1712577720,1.26204,1.26220,1.26200,1.26220,0.665248,0.687943,0.659574,0.687943,0
8982630,1712577780,1.26220,1.26230,1.26219,1.26230,0.687943,0.702128,0.686525,0.702128,0
8982631,1712577840,1.26228,1.26230,1.26211,1.26214,0.699291,0.702128,0.675177,0.679433,0
8982632,1712577900,1.26216,1.26222,1.26204,1.26206,0.682270,0.690780,0.665248,0.668085,0
8982633,1712577960,1.26206,1.26216,1.26196,1.26196,0.668085,0.682270,0.653901,0.653901,0
8982634,1712578020,1.26196,1.26196,1.26178,1.26189,0.653901,0.653901,0.628369,0.643972,0
8982635,1712578080,1.26187,1.26187,1.26165,1.26170,0.641135,0.641135,0.609929,0.617021,0
8982636,1712578140,1.26171,1.26176,1.26165,1.26175,0.618440,0.625532,0.609929,0.624113,0
8982637,1712578200,1.26175,1.26182,1.26169,1.26177,0.624113,0.634043,0.615603,0.626950,1
8982638,1712578260,1.26175,1.26179,1.26174,1.26179,0.624113,0.629787,0.622695,0.629787,1
8982639,1712578320,1.26178,1.26186,1.26166,1.26170,0.628369,0.639716,0.611348,0.617021,0
8982640,1712578380,1.26169,1.26176,1.26164,1.26167,0.615603,0.625532,0.608511,0.612766,0
8982641,1712578440,1.26168,1.26173,1.26165,1.26166,0.614184,0.621277,0.609929,0.611348,0
8982642,1712578500,1.26166,1.26167,1.26152,1.26152,0.611348,0.612766,0.591489,0.591489,0
8982643,1712578560,1.26151,1.26174,1.26146,1.26174,0.590071,0.622695,0.582979,0.622695,1
8982644,1712578620,1.26173,1.26180,1.26170,1.26177,0.621277,0.631206,0.617021,0.626950,1
8982645,1712578680,1.26176,1.26178,1.26164,1.26168,0.625532,0.628369,0.608511,0.614184,0
8982646,1712578740,1.26167,1.26186,1.26166,1.26184,0.612766,0.639716,0.611348,0.636879,1
8982647,1712578800,1.26184,1.26197,1.26184,1.26196,0.636879,0.655319,0.636879,0.653901,1
8982648,1712578860,1.26196,1.26206,1.26194,1.26206,0.653901,0.668085,0.651064,0.668085,1
8982649,1712578920,1.26205,1.26206,1.26198,1.26203,0.666667,0.668085,0.656738,0.663830,0
8982650,1712578980,1.26203,1.26207,1.26201,1.26206,0.663830,0.669504,0.660993,0.668085,1
8982651,1712579040,1.26208,1.26218,1.26205,1.26210,0.670922,0.685106,0.666667,0.673759,1
8982652,1712579100,1.26211,1.26227,1.26210,1.26226,0.675177,0.697872,0.673759,0.696454,1
8982653,1712579160,1.26225,1.26253,1.26225,1.26252,0.695035,0.734752,0.695035,0.733333,0
8982654,1712579220,1.26247,1.26265,1.26246,1.26264,0.726241,0.751773,0.724823,0.750355,0
8982655,1712579280,1.26263,1.26265,1.26256,1.26264,0.748936,0.751773,0.739007,0.750355,0
8982656,1712579340,1.26265,1.26267,1.26261,1.26266,0.751773,0.754610,0.746099,0.753191,0
8982657,1712579400,1.26267,1.26277,1.26267,1.26275,0.754610,0.768794,0.754610,0.765957,0
8982658,1712579460,1.26276,1.26276,1.26263,1.26263,0.767376,0.767376,0.748936,0.748936,0
8982659,1712579520,1.26263,1.26269,1.26256,1.26269,0.748936,0.757447,0.739007,0.757447,0
8982660,1712579580,1.26267,1.26275,1.26262,1.26263,0.754610,0.765957,0.747518,0.748936,0
8982661,1712579640,1.26262,1.26266,1.26262,1.26265,0.747518,0.753191,0.747518,0.751773,0
8982662,1712579700,1.26265,1.26275,1.26265,1.26273,0.751773,0.765957,0.751773,0.763121,0
8982663,1712579760,1.26273,1.26274,1.26251,1.26252,0.763121,0.764539,0.731915,0.733333,0
8982664,1712579820,1.26251,1.26253,1.26228,1.26229,0.731915,0.734752,0.699291,0.700709,0
8982665,1712579880,1.26229,1.26233,1.26222,1.26222,0.700709,0.706383,0.690780,0.690780,0
8982666,1712579940,1.26222,1.26222,1.26216,1.26220,0.690780,0.690780,0.682270,0.687943,0
8982667,1712580000,1.26220,1.26245,1.26212,1.26238,0.687943,0.723404,0.676596,0.713475,1
8982668,1712580060,1.26237,1.26244,1.26234,1.26241,0.712057,0.721986,0.707801,0.717730,0
8982669,1712580120,1.26242,1.26242,1.26225,1.26231,0.719149,0.719149,0.695035,0.703546,0
8982670,1712580180,1.26232,1.26234,1.26213,1.26232,0.704965,0.707801,0.678014,0.704965,0
8982671,1712580240,1.26231,1.26244,1.26229,1.26243,0.703546,0.721986,0.700709,0.720567,0
8982672,1712580300,1.26242,1.26269,1.26242,1.26268,0.719149,0.757447,0.719149,0.756028,0
8982673,1712580360,1.26269,1.26270,1.26253,1.26256,0.757447,0.758865,0.734752,0.739007,0

In [11]:
df.target.value_counts()

target
0    7381108
2     818044
1     782081
Name: count, dtype: int64

In [12]:
df.to_csv('my_csv.csv', index=False)

In [13]:
df.head()

,time,open,high,low,close,open_normalized,high_normalized,low_normalized,close_normalized,target
1441,915553980,1.6548,1.6550,1.6540,1.6544,0.099476,0.109948,0.057592,0.078534,2
1442,915554040,1.6547,1.6551,1.6545,1.6551,0.094241,0.115183,0.083770,0.115183,0
1443,915554100,1.6548,1.6548,1.6541,1.6547,0.099476,0.099476,0.062827,0.094241,0
1444,915554160,1.6553,1.6558,1.6550,1.6558,0.125654,0.151832,0.109948,0.151832,0
1445,915554220,1.6552,1.6555,1.6551,1.6555,0.120419,0.136126,0.115183,0.136126,0